#!/usr/bin/env python3
"""Generate the agent-browsable reference under .claude/skills/van-api/reference/.

The spec is ~114k tokens — far too much for an agent to load to answer one
question. This slices it into files small enough to read on demand and named
predictably enough to reach without consulting an index:

    reference/INDEX.md                  every operation on one line, with the
                                        user vocabulary from x-keywords
    reference/COVERAGE.md               what is *not* in the spec, from STATUS.md
    reference/operations/<operationId>.md
    reference/schemas/<SchemaName>.md
    reference/behaviors/<transcript id>.md

SKILL.md and reference/recipes/ are hand-written and never touched here.

Two conventions the whole thing rests on:

  * Filenames are operationIds and transcript ids, so an agent that has seen
    either in the spec can construct the path without a lookup.
  * Every property is one table row, newlines collapsed, so a single
    `grep -rn phoneNumber reference/` returns the full description as one hit.
"""

import json
import os
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
SKILL = REPO / ".claude" / "skills" / "van-api"
OUT = SKILL / "reference"

# Hand-written prose can still carry spec-derived tables, kept in sync through
# markers rather than by hand:
#     <!-- BEGIN GENERATED: routing -->  ...  <!-- END GENERATED: routing -->
BLOCK = re.compile(
    r"(<!-- BEGIN GENERATED: (?P<name>[\w-]+) -->\n)(?P<body>.*?)(<!-- END GENERATED: (?P=name) -->)",
    re.DOTALL,
)

HTTP_METHODS = ("get", "put", "post", "delete", "patch", "options", "head")

# A schema earns its own page once inlining it at every use site costs more
# than the extra file read. 1600 chars ~ 400 tokens is where that crosses over
# for this spec; everything smaller is duplicated wherever it is used.
OWN_PAGE_CHARS = 1600

# The error contract is identical on almost every operation — 401/429/500 on all
# fifteen, 400 on thirteen. Repeating it per page costs ~8k tokens of pure
# duplication, so it lives once in ERRORS.md and the tables link to it.
ERROR_SCHEMAS = {"ErrorResponse", "AspNetError", "Error"}

BANNER = "<!-- Generated by `make agent-docs` from openapi.json, transcripts/ and STATUS.md. Do not edit by hand. -->"


# --------------------------------------------------------------------------
# helpers
# --------------------------------------------------------------------------


def cell(text):
    """Collapse a description into one table cell: no newlines, no bare pipes."""
    if not text:
        return ""
    return re.sub(r"\s+", " ", str(text)).replace("|", "\\|").strip()


def operations(spec):
    """Yield (path, method, operation) for every operation in the spec."""
    for path, item in spec["paths"].items():
        for method, op in item.items():
            if method in HTTP_METHODS:
                yield path, method, op


def enum_of(schemas, schema):
    """Allowed values, looking through arrays — an array's enum sits on `items`."""
    resolved = schemas.deref(schema)
    if resolved.get("type") == "array":
        resolved = schemas.deref(resolved.get("items", {}))
    return resolved.get("enum")


def write(path, lines):
    path.parent.mkdir(parents=True, exist_ok=True)
    body = "\n".join(lines).rstrip() + "\n"
    body = re.sub(r"\n{3,}", "\n\n", body)
    path.write_text(body)


# --------------------------------------------------------------------------
# schema rendering
# --------------------------------------------------------------------------


class Schemas:
    """Resolves $refs, deciding at each one whether to link out or inline."""

    def __init__(self, spec):
        self.all = spec["components"]["schemas"]
        self.own_page = {
            name
            for name, schema in self.all.items()
            if len(json.dumps(schema)) >= OWN_PAGE_CHARS
        }

    def deref(self, schema):
        """Follow $ref and flatten allOf into a single object schema."""
        seen = set()
        while isinstance(schema, dict) and "$ref" in schema:
            name = schema["$ref"].rsplit("/", 1)[-1]
            if name in seen:
                return {}
            seen.add(name)
            schema = self.all.get(name, {})
        if isinstance(schema, dict) and "allOf" in schema:
            merged = {"type": "object", "properties": {}, "required": []}
            for part in schema["allOf"]:
                part = self.deref(part)
                merged["properties"].update(part.get("properties", {}))
                merged["required"] += part.get("required", [])
                for key in ("description", "type"):
                    if key in part and key not in merged:
                        merged[key] = part[key]
            for key, value in schema.items():
                if key != "allOf":
                    merged.setdefault(key, value)
            return merged
        return schema if isinstance(schema, dict) else {}

    def ref_name(self, schema):
        """The schema name if this is a bare $ref, else None."""
        if isinstance(schema, dict) and "$ref" in schema:
            return schema["$ref"].rsplit("/", 1)[-1]
        return None

    def type_of(self, schema, depth, base="../"):
        """Render the Type column, linking out to any schema with its own page.

        `base` is the path back to reference/ from the page being written, so
        the same renderer serves pages at the root and in subdirectories.
        """
        name = self.ref_name(schema)
        if name and name in self.own_page:
            return f"[{name}]({base}schemas/{name}.md)"
        if name in ERROR_SCHEMAS:
            return f"[{name}]({base}ERRORS.md#{name.lower()})"
        resolved = self.deref(schema)
        for key in ("oneOf", "anyOf"):
            if resolved.get(key):
                joiner = " or " if key == "oneOf" else " and/or "
                return joiner.join(self.type_of(alt, depth, base) for alt in resolved[key])
        kind = resolved.get("type")
        if isinstance(kind, list):
            nullable = "null" in kind
            kind = next((k for k in kind if k != "null"), "any")
            suffix = " or null" if nullable else ""
        else:
            suffix = ""
        if kind == "array":
            return f"array of {self.type_of(resolved.get('items', {}), depth, base)}{suffix}"
        if kind == "object" and resolved.get("properties"):
            return f"object{suffix}"
        fmt = resolved.get("format")
        return f"{kind or 'any'}{f' ({fmt})' if fmt else ''}{suffix}"

    def rows(self, schema, base="../", prefix="", depth=0, seen=None):
        """One row per property, nested objects flattened to dotted paths."""
        seen = set(seen or ())
        name = self.ref_name(schema)
        if name:
            if name in seen:
                return []
            seen.add(name)
        resolved = self.deref(schema)
        if resolved.get("type") == "array":
            return self.rows(resolved.get("items", {}), base, prefix, depth, seen)

        required = set(resolved.get("required", []))
        out = []
        for prop, sub in (resolved.get("properties") or {}).items():
            path = f"{prop}" if not prefix else f"{prefix}.{prop}"
            sub_name = self.ref_name(sub)
            resolved_sub = self.deref(sub)

            notes = [resolved_sub.get("description") or sub.get("description") or ""]
            enum = enum_of(self, sub)
            if enum:
                notes.append("One of: " + ", ".join(f"`{v}`" for v in enum) + ".")
            examples = resolved_sub.get("examples") or (
                [resolved_sub["example"]] if "example" in resolved_sub else []
            )
            if examples:
                notes.append("e.g. " + ", ".join(f"`{e}`" for e in examples[:2]))

            out.append(
                f"| `{path}`{' *' if prop in required else ''} "
                f"| {self.type_of(sub, depth, base)} | {cell(' '.join(n for n in notes if n))} |"
            )

            # Recurse into inline objects and arrays of them, but stop at
            # anything that has its own page — that is what the link is for.
            if sub_name and sub_name in self.own_page:
                continue
            if depth >= 3:
                continue
            target = resolved_sub
            if target.get("type") == "array":
                item_name = self.ref_name(target.get("items", {}))
                if item_name and item_name in self.own_page:
                    continue
                target = self.deref(target.get("items", {}))
            if target.get("properties"):
                out += self.rows(target, base, path, depth + 1, seen)
        return out

    def table(self, schema, base="../", title=None):
        rows = self.rows(schema, base)
        if not rows:
            resolved = self.deref(schema)
            desc = resolved.get("description")
            return [f"_{cell(desc)}_"] if desc else ["_No documented properties._"]
        lines = []
        if title:
            lines.append(title)
        resolved = self.deref(schema)
        if resolved.get("description"):
            lines += [resolved["description"], ""]
        lines += ["| Property | Type | Notes |", "| --- | --- | --- |", *rows]
        lines += ["", "`*` = required."]
        return lines


# --------------------------------------------------------------------------
# transcripts
# --------------------------------------------------------------------------


def load_transcripts():
    """Transcript id -> record, plus operation-pointer -> [transcript]."""
    by_id, by_pointer = {}, {}
    for path in sorted((REPO / "transcripts").glob("*.json")):
        t = json.loads(path.read_text())
        by_id[t["id"]] = t
        for pointer in t.get("spec", []):
            by_pointer.setdefault(pointer, []).append(t)
    return by_id, by_pointer


def pointer_for(path, method):
    return f"#/paths/~1{path.lstrip('/').replace('/', '~1')}/{method}"


def render_transcript(t):
    """A behavior page: the claim, then the exchanges as runnable curl."""
    lines = [
        BANNER,
        "",
        f"# {t['title']}",
        "",
        f"**Claim.** {t['claim']}",
        "",
    ]
    ops = t.get("spec", [])
    if ops:
        pretty = ", ".join(f"`{p.split('/paths/')[-1]}`" for p in ops)
        lines += [f"Applies to: {pretty}", ""]
    lines += ["## Observed exchange", ""]
    for entry in t.get("entries", []):
        if entry.get("kind") == "comment":
            lines += ["", f"_{entry['text']}_", ""]
            continue
        req, resp = entry.get("request", {}), entry.get("response", {})
        role = entry.get("role", "subject")
        prefix = "" if role == "subject" else f"({role}) "
        line = f"{prefix}{req.get('method', '?')} {req.get('url', req.get('path', ''))}"
        block = ["```http", line]
        if req.get("body") is not None:
            block += ["", json.dumps(req["body"], indent=2)]
        block += ["", f"→ {resp.get('status', '?')}"]
        location = (resp.get("headers") or {}).get("location")
        if location:
            block.append(f"  Location: {location}")
        if resp.get("body") is not None:
            body = json.dumps(resp["body"], indent=2)
            if len(body) > 1200:
                body = body[:1200] + "\n… truncated"
            block.append(body)
        block.append("```")
        lines += block
    return lines


# --------------------------------------------------------------------------
# operation pages
# --------------------------------------------------------------------------


def example_call(spec, path, method, op):
    """Synthesise the shortest curl that exercises the operation.

    The x-codeSamples in the spec are multi-step scripts of 1.5k-8k characters
    — too heavy for the top of a reference page. They stay reachable through
    the behavior pages; this is just the shape of one call.
    """
    url = path
    query = []
    for param in op.get("parameters", []):
        value = param.get("example")
        if value is None:
            continue
        if param["in"] == "path":
            url = url.replace("{" + param["name"] + "}", str(value))
        elif param["in"] == "query" and param.get("required"):
            query.append(f"{param['name']}={value}")

    # No required query parameters is not the same as none worth showing: an
    # endpoint that refuses an empty query needs one in the example.
    if not query and method == "get":
        for param in op.get("parameters", []):
            if param["in"] == "query" and param.get("example") is not None:
                query.append(f"{param['name']}={param['example']}")
                break

    full = url + ("?" + "&".join(query) if query else "")
    lines = ["```bash", f"curl -sS -X {method.upper()} \\"]
    lines.append(f"  'https://api.securevan.com/v4{full}' \\")
    lines.append('  -u "app-name:$NGP_API_KEY|1" \\')

    body = None
    content = (op.get("requestBody") or {}).get("content", {}).get("application/json", {})
    examples = content.get("examples") or {}
    if examples:
        chosen = examples.get("minimal") or next(iter(examples.values()))
        body = chosen.get("value")
    if body is not None:
        lines.append("  -H 'Content-Type: application/json' \\")
        payload = json.dumps(body, indent=2)
        lines.append(f"  -d '{payload}'")
    else:
        lines[-1] = lines[-1].rstrip(" \\")
    lines.append("```")
    return lines


def render_operation(spec, schemas, path, method, op, transcripts):
    op_id = op["operationId"]
    lines = [
        BANNER,
        "",
        f"# {op_id} — {method.upper()} {path}",
        "",
        op["summary"],
        "",
    ]

    # Front-loaded, because an agent that stops reading after the first screen
    # should still have been warned. Every claim here is a recorded exchange.
    if transcripts:
        lines += ["## Verified behaviors", ""]
        for t in transcripts:
            lines.append(f"- **{t['title']}** — {t['claim']} ([replay](../behaviors/{t['id']}.md))")
        lines.append("")

    lines += ["## Behavior", "", op["description"], ""]

    discrepancies = collect_discrepancies(op)
    if discrepancies:
        lines += ["## Differs from the official docs", ""]
        lines += [f"- **{where}** — {note}" for where, note in discrepancies]
        lines.append("")

    lines += ["## Example", "", *example_call(spec, path, method, op), ""]

    params = op.get("parameters", [])
    for kind, heading in (("path", "Path parameters"), ("query", "Query parameters")):
        subset = [p for p in params if p["in"] == kind]
        if not subset:
            continue
        lines += [f"## {heading}", "", "| Name | Type | Notes |", "| --- | --- | --- |"]
        for p in subset:
            notes = [p.get("description", "")]
            enum = enum_of(schemas, p.get("schema", {}))
            if enum:
                notes.append("One of: " + ", ".join(f"`{v}`" for v in enum) + ".")
            star = " *" if p.get("required") else ""
            lines.append(
                f"| `{p['name']}`{star} | {schemas.type_of(p.get('schema', {}), 0)} "
                f"| {cell(' '.join(n for n in notes if n))} |"
            )
        lines += ["", "`*` = required.", ""]

    body = op.get("requestBody")
    if body:
        media = body.get("content", {}).get("application/json", {})
        schema = media.get("schema", {})
        required = " (required)" if body.get("required") else " (optional)"
        name = schemas.ref_name(schema)
        lines += [f"## Request body{required}", ""]
        if name and name in schemas.own_page:
            lines += [f"See [{name}](../schemas/{name}.md).", ""]
        else:
            lines += [*schemas.table(schema), ""]

    lines += ["## Responses", "", "| Status | Meaning | Body |", "| --- | --- | --- |"]
    shared = {}
    for code, resp in op["responses"].items():
        shared_name = resp["$ref"].rsplit("/", 1)[-1] if "$ref" in resp else None
        resolved = spec["components"]["responses"][shared_name] if shared_name else resp
        schema = (resolved.get("content", {}).get("application/json", {}) or {}).get("schema", {})
        name = schemas.ref_name(schema)
        if name and name in schemas.own_page:
            shape = f"[{name}](../schemas/{name}.md)"
        elif name in ERROR_SCHEMAS:
            shape = f"[{name}](../ERRORS.md#{name.lower()})"
        elif name:
            shape = f"`{name}`"
        elif schema:
            shape = schemas.type_of(schema, 0)
        else:
            shape = "_empty_"

        meaning = cell(resolved.get("description"))
        if shared_name:
            # The shared descriptions run to 700 characters and say the same
            # thing on every page. First sentence here, the rest in ERRORS.md.
            head = re.split(r"(?<=[.!?])\s", meaning, maxsplit=1)[0]
            meaning = f"{head} ([details](../ERRORS.md#{shared_name.lower()}))"
            shared[shared_name] = resolved
        lines.append(f"| `{code}` | {meaning} | {shape} |")
    lines.append("")

    # Inline the small operation-specific response schemas the table only
    # named, so the common case needs no second file read.
    shown = set()
    for code, resp in op["responses"].items():
        if "$ref" in resp:
            continue
        schema = (resp.get("content", {}).get("application/json", {}) or {}).get("schema", {})
        name = schemas.ref_name(schema)
        if not name or name in schemas.own_page or name in ERROR_SCHEMAS or name in shown:
            continue
        shown.add(name)
        lines += [f"### `{code}` body — {name}", "", *schemas.table(schema), ""]

    links = {}
    for resp in op["responses"].values():
        links.update(resp.get("links") or {})
    if links:
        lines += ["## What to call next", ""]
        for label, link in links.items():
            target = link.get("operationId", label)
            lines.append(f"- [`{target}`]({target}.md) — {cell(link.get('description'))}")
        lines.append("")

    return lines


def collect_discrepancies(node, crumbs=()):
    """Every x-docs-discrepancy at or under an operation, with a readable label."""
    out = []
    if isinstance(node, dict):
        if "x-docs-discrepancy" in node:
            label = " / ".join(str(c) for c in crumbs) or "the operation"
            out.append((label, node["x-docs-discrepancy"]))
        for key, value in node.items():
            if key == "x-docs-discrepancy":
                continue
            out += collect_discrepancies(value, crumbs + (key,))
    elif isinstance(node, list):
        for i, value in enumerate(node):
            crumb = value.get("name", str(i)) if isinstance(value, dict) else str(i)
            out += collect_discrepancies(value, crumbs + (crumb,))
    return out


# --------------------------------------------------------------------------
# index and coverage
# --------------------------------------------------------------------------


def render_index(spec, by_pointer):
    lines = [
        BANNER,
        "",
        "# Operation index",
        "",
        "Every operation the spec covers. `Search terms` is the vocabulary a",
        "request is likely to use — grep this file for the user's own words",
        "before guessing at an operationId.",
        "",
        "Pages are at `operations/<operationId>.md`.",
        "",
        "| Operation | Endpoint | What it does | Search terms |",
        "| --- | --- | --- | --- |",
    ]
    for path, method, op in operations(spec):
        op_id = op["operationId"]
        keywords = ", ".join(op.get("x-keywords", []))
        lines.append(
            f"| [`{op_id}`](operations/{op_id}.md) | `{method.upper()} {path}` "
            f"| {cell(op['summary'])} | {cell(keywords)} |"
        )

    lines += [
        "",
        "## Verified behaviors",
        "",
        "Recorded request/response exchanges, at `behaviors/<id>.md`. Each one is",
        "already summarised at the top of the operation page it applies to, so",
        "read these only when you want the actual traffic.",
        "",
        "| Behavior | Title |",
        "| --- | --- |",
    ]
    everything = {t["id"]: t for ts in by_pointer.values() for t in ts}
    for t in sorted(everything.values(), key=lambda t: t["id"]):
        lines.append(f"| [`{t['id']}`](behaviors/{t['id']}.md) | {cell(t['title'])} |")
    return lines


def render_errors(spec, schemas):
    """The error contract, once, instead of on all fifteen operation pages."""
    lines = [
        BANNER,
        "",
        "# Errors",
        "",
        "Every operation can return `401`, `429` and `500`; most can also return",
        "`400`. The operation pages name the status and link here for the detail.",
        "",
    ]
    for name, resp in spec["components"]["responses"].items():
        lines += [f"## {name}", "", resp.get("description", ""), ""]
        schema = (resp.get("content", {}).get("application/json", {}) or {}).get("schema", {})
        shape = schemas.type_of(schema, 0, base="") if schema else "_empty body_"
        lines += [f"Body: {shape}", ""]

    lines += ["## Error body shapes", ""]
    for name in ("ErrorResponse", "AspNetError", "Error"):
        if name not in schemas.all:
            continue
        lines += [f"### {name}", "", *schemas.table(schemas.all[name], base=""), ""]
    return lines


def status_rows():
    """Parse the endpoint survey table out of STATUS.md.

    Only the five-column survey table is wanted; STATUS.md also carries a
    two-column table of sandbox fixtures further down.
    """
    for line in (REPO / "STATUS.md").read_text().splitlines():
        line = line.strip()
        if not line.startswith("|") or not line.endswith("|"):
            continue
        cells = [c.strip() for c in line[1:-1].split("|")]
        if len(cells) != 5:
            continue
        if cells[0] == "Endpoint group" or set(cells[0]) <= set("-: "):
            continue
        yield cells


def render_coverage():
    """Turn the STATUS.md survey into a boundary map.

    This is the file that lets an agent answer "you cannot do that with this
    spec" in one read instead of discovering it over a dozen failed requests.
    """
    covered, researched, unknown = [], [], []
    for group, paths, _sources, status, _last in status_rows():
        row = (group, paths, status)
        plain = status.lower()
        if "validated" in plain or "spec'd" in plain:
            covered.append(row)
        elif "unresearched" in plain:
            unknown.append(row)
        else:
            researched.append(row)

    lines = [
        BANNER,
        "",
        "# Coverage — what this spec does and does not cover",
        "",
        "The NGP VAN API is much larger than this spec. Before concluding that",
        "something is impossible, check which of the three sections below it",
        "falls into. **Never invent an endpoint that is not listed here.**",
        "",
        "## 1. In the spec, verified against the live API",
        "",
        "These have pages under `operations/`. Behavior in them has been probed.",
        "",
        "| Endpoint group | Paths | Status |",
        "| --- | --- | --- |",
    ]
    lines += [f"| {cell(g)} | {cell(p)} | {cell(s)} |" for g, p, s in covered]

    lines += [
        "",
        "## 2. Real endpoints, researched but deliberately not in the spec",
        "",
        "These exist. The spec omits them for the reason given — usually that the",
        "sandbox key cannot reach them, so the success shape was never observed.",
        "You can still call them; you just have no schema for the response.",
        "",
        "| Endpoint group | Paths | Why not spec'd |",
        "| --- | --- | --- |",
    ]
    lines += [f"| {cell(g)} | {cell(p)} | {cell(s)} |" for g, p, s in researched]

    lines += [
        "",
        "## 3. Known to exist, not yet researched",
        "",
        "Paths gathered from the official docs and the NGPVAN/van-cli source but",
        "never probed. **If a request needs one of these, say so rather than",
        "improvising with the endpoints in section 1.** Bulk questions — totals",
        "across a whole database, exports, anything that would otherwise need",
        "thousands of paged requests — almost always land here, under Export Jobs,",
        "Saved Lists or Changed Entity Export Jobs.",
        "",
        "| Endpoint group | Paths |",
        "| --- | --- |",
    ]
    lines += [f"| {cell(g)} | {cell(p)} |" for g, p, _ in unknown]

    lines += [
        "",
        "## Confirmed absent",
        "",
        "- `GET /people/quickSearch` — 404 \"No HTTP resource\". It does not exist,",
        "  in any casing. Use `GET /people` (searchPeople).",
        "- There is no count-by-attribute or aggregate endpoint of any kind. The",
        "  only total the API volunteers is `count` in the pagination envelope,",
        "  which counts matches for a query you already had to specify.",
        "",
        "## Where the evidence lives",
        "",
        "- Research status and sandbox notes: [STATUS.md](../../../../STATUS.md)",
        "- Departures from the official docs: [DISCREPANCIES.md](../../../../DISCREPANCIES.md)",
        "- Per-field evidence: the `x-provenance` fields in",
        "  [openapi.json](../../../../openapi.json), omitted from these pages.",
    ]
    return lines


# --------------------------------------------------------------------------


def render_routing(spec, base):
    """The task -> operation table, from each operation's x-task."""
    lines = ["| Task | Operation |", "| --- | --- |"]
    for _path, _method, op in operations(spec):
        task = op.get("x-task")
        if not task:
            raise SystemExit(f"{op['operationId']} has no x-task — add one to the spec")
        op_id = op["operationId"]
        lines.append(f"| {cell(task)} | [`{op_id}`]({base}operations/{op_id}.md) |")
    return lines


def render_traps(spec, base):
    """The cross-cutting gotcha list, from the spec's root-level x-traps."""
    op_ids = {op["operationId"] for _p, _m, op in operations(spec)}
    behavior_ids = set(load_transcripts()[0])

    lines = []
    for trap in spec.get("x-traps", []):
        links = []
        for ref in trap.get("see", []):
            if ref in op_ids:
                links.append(f"[`{ref}`]({base}operations/{ref}.md)")
            elif ref in behavior_ids:
                links.append(f"[`{ref}`]({base}behaviors/{ref}.md)")
            else:
                raise SystemExit(
                    f"x-traps entry points at '{ref}', which is neither an "
                    f"operationId nor a transcript id"
                )
        suffix = f" ({', '.join(links)})" if links else ""
        lines.append(f"- {trap['text']}{suffix}")
    return lines


BLOCKS = {"routing": render_routing, "traps": render_traps}


def sync_blocks(spec, check):
    """Refresh the generated blocks inside the hand-written prose.

    Returns the paths whose blocks were out of date.
    """
    stale = []
    for path in sorted(SKILL.rglob("*.md")):
        if OUT in path.parents and path.parent.name != "recipes":
            continue  # fully generated already
        original = path.read_text()
        if "<!-- BEGIN GENERATED:" not in original:
            continue
        # How to get from this file's directory back into reference/.
        base = os.path.relpath(OUT, path.parent) + "/"
        base = "" if base == "./" else base

        def replace(m):
            name = m.group("name")
            if name not in BLOCKS:
                raise SystemExit(f"{path.name}: unknown generated block '{name}'")
            body = "\n".join(BLOCKS[name](spec, base))
            return f"{m.group(1)}\n{body}\n\n{m.group(4)}"

        updated = BLOCK.sub(replace, original)
        if updated == original:
            continue
        if check:
            stale.append(str(path.relative_to(SKILL)))
        else:
            path.write_text(updated)
    return stale


def check_spec_symlink():
    """The skill ships the spec itself, as a symlink so it can never be a stale copy."""
    link = SKILL / "openapi.json"
    want = os.path.relpath(REPO / "openapi.json", SKILL)
    if not link.is_symlink():
        return f"{link.relative_to(SKILL)} must be a symlink to {want}"
    if os.readlink(link) != want:
        return f"{link.relative_to(SKILL)} points at {os.readlink(link)}, expected {want}"
    if not link.resolve().exists():
        return f"{link.relative_to(SKILL)} is a broken symlink"
    return None


def check_references():
    """Every relative link in the skill must resolve.

    This is what stops the hand-written prose rotting silently: rename an
    operation or delete a transcript and the recipes that pointed at it fail CI.
    """
    broken = []
    for path in sorted(SKILL.rglob("*.md")):
        for m in re.finditer(r"\]\(([^)]+)\)", path.read_text()):
            target = m.group(1).split("#")[0]
            if not target or target.startswith(("http://", "https://", "mailto:")):
                continue
            if not (path.parent / target).resolve().exists():
                broken.append(f"{path.relative_to(SKILL)} -> {target}")
    return broken


def build(spec):
    schemas = Schemas(spec)
    by_id, by_pointer = load_transcripts()
    files = {}

    for path, method, op in operations(spec):
        related = by_pointer.get(pointer_for(path, method), [])
        related = sorted(related, key=lambda t: t["id"])
        files[f"operations/{op['operationId']}.md"] = render_operation(
            spec, schemas, path, method, op, related
        )

    for name in sorted(schemas.own_page):
        schema = schemas.all[name]
        used_by = [
            op["operationId"]
            for _, _, op in operations(spec)
            if f'"#/components/schemas/{name}"' in json.dumps(op)
        ]
        body = [BANNER, "", f"# {name}", ""]
        if used_by:
            refs = ", ".join(f"[`{o}`](../operations/{o}.md)" for o in used_by)
            body += [f"Used directly by: {refs}", ""]
        body += schemas.table(schema)
        files[f"schemas/{name}.md"] = body

    for t in by_id.values():
        files[f"behaviors/{t['id']}.md"] = render_transcript(t)

    files["INDEX.md"] = render_index(spec, by_pointer)
    files["COVERAGE.md"] = render_coverage()
    files["ERRORS.md"] = render_errors(spec, schemas)
    return files


def main():
    check = "--check" in sys.argv
    spec = json.loads((REPO / "openapi.json").read_text())
    files = build(spec)

    stale = []
    for rel, lines in files.items():
        target = OUT / rel
        body = re.sub(r"\n{3,}", "\n\n", "\n".join(lines).rstrip() + "\n")
        if check:
            if not target.exists() or target.read_text() != body:
                stale.append(rel)
        else:
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_text(body)

    # Files left behind by a renamed operation or a deleted transcript would
    # otherwise keep being served as current.
    expected = {OUT / rel for rel in files}
    for existing in OUT.rglob("*.md"):
        if existing.parent.name == "recipes" or existing in expected:
            continue
        if check:
            stale.append(f"{existing.relative_to(OUT)} (orphaned)")
        else:
            existing.unlink()

    stale += [f"{rel} (generated block)" for rel in sync_blocks(spec, check)]

    # Run last: the link check is only meaningful once everything is written.
    broken = check_references()
    symlink_problem = check_spec_symlink()
    if symlink_problem:
        broken.append(symlink_problem)

    if check:
        if stale:
            print("agent docs are stale — run `make agent-docs` and commit:", file=sys.stderr)
            for rel in sorted(stale):
                print(f"  {rel}", file=sys.stderr)
        if broken:
            print("dangling references in the skill:", file=sys.stderr)
            for ref in broken:
                print(f"  {ref}", file=sys.stderr)
        if stale or broken:
            sys.exit(1)
        print("agent docs are up to date")
    else:
        if broken:
            print("dangling references in the skill:", file=sys.stderr)
            for ref in broken:
                print(f"  {ref}", file=sys.stderr)
            sys.exit(1)
        print(f"wrote {len(files)} files to {OUT.relative_to(REPO)}")


if __name__ == "__main__":
    main()
