#!/usr/bin/env python3
"""Generate DISCREPANCIES.md from x-docs-discrepancy fields in openapi.json."""

import json
import sys

HEADER = """\
# Deviations from the official docs

Generated by `make discrepancies` from the `x-docs-discrepancy` fields in
[openapi.json](openapi.json) — do not edit by hand.

The spec itself records only observed behavior; this file records where that
behavior deviates from the official docs at <https://docs.ngpvan.com>.
Research status and evidence live in `x-provenance` fields and
[STATUS.md](STATUS.md).
"""


HTTP_METHODS = {"get", "put", "post", "delete", "options", "head", "patch", "trace"}


def label(crumbs):
    """Human-readable location from the trail of keys leading to the annotation."""
    if len(crumbs) >= 3 and crumbs[0] == "paths" and crumbs[2] in HTTP_METHODS:
        loc = f"{crumbs[2].upper()} {crumbs[1]}"
        rest = crumbs[3:]
        if rest[:1] == ["parameters"] and len(rest) >= 2:
            return f"{loc} parameter `{rest[1]}`"
        return f"{loc}" + (f" ({' / '.join(rest)})" if rest else "")
    if crumbs[:2] == ["components", "schemas"]:
        name = crumbs[2] + "".join(f".{c}" for c in crumbs[3:] if c not in ("properties", "items"))
        return f"schema `{name}`"
    return "/".join(crumbs) or "/"


def walk(node, crumbs=(), parent_key=None):
    if isinstance(node, dict):
        if "x-docs-discrepancy" in node:
            yield label(list(crumbs)), node["x-docs-discrepancy"]
        for key, value in node.items():
            yield from walk(value, crumbs + (key,), key)
    elif isinstance(node, list):
        for i, value in enumerate(node):
            # For parameter lists, identify the entry by its name instead of its index.
            crumb = value.get("name", str(i)) if isinstance(value, dict) and parent_key == "parameters" else str(i)
            yield from walk(value, crumbs + (crumb,), parent_key)


def main():
    spec_path = sys.argv[1] if len(sys.argv) > 1 else "openapi.json"
    with open(spec_path) as f:
        spec = json.load(f)
    print(HEADER)
    for where, note in walk(spec):
        print(f"- **{where}** — {note}")


if __name__ == "__main__":
    main()
